CREATE DATABASE IF NOT EXISTS SUPPLYSHIELD;
CREATE SCHEMA IF NOT EXISTS SUPPLYSHIELD.RAW;
CREATE SCHEMA IF NOT EXISTS SUPPLYSHIELD.CURATED;
CREATE SCHEMA IF NOT EXISTS SUPPLYSHIELD.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS SUPPLYSHIELD.AI;

USE DATABASE SUPPLYSHIELD;

CREATE OR REPLACE TABLE RAW.SUPPLIERS (
 SUPPLIER_ID STRING, SUPPLIER_NAME STRING, COUNTRY STRING,
 BASE_LEAD_DAYS NUMBER, RELIABILITY_SCORE NUMBER(5,2)
);
CREATE OR REPLACE TABLE RAW.MEDICINES (
 MEDICINE_ID STRING, MEDICINE_NAME STRING, CRITICALITY STRING,
 UNIT_COST NUMBER(12,2), DAILY_DEMAND NUMBER(12,2), SAFETY_DAYS NUMBER
);
CREATE OR REPLACE TABLE RAW.PLANTS (
 PLANT_ID STRING, PLANT_NAME STRING, CITY STRING
);
CREATE OR REPLACE TABLE RAW.INVENTORY (
 PLANT_ID STRING, MEDICINE_ID STRING, ON_HAND NUMBER, AS_OF_DATE DATE
);
CREATE OR REPLACE TABLE RAW.SHIPMENTS (
 SHIPMENT_ID STRING, SUPPLIER_ID STRING, PLANT_ID STRING, MEDICINE_ID STRING,
 QTY NUMBER, PROMISED_DATE DATE, EXPECTED_DATE DATE, STATUS STRING
);
CREATE OR REPLACE TABLE RAW.ORDERS (
 ORDER_ID STRING, PLANT_ID STRING, MEDICINE_ID STRING, CUSTOMER_ID STRING,
 QTY NUMBER, REQUIRED_DATE DATE, PRIORITY STRING
);
CREATE OR REPLACE TABLE RAW.CUSTOMERS (
 CUSTOMER_ID STRING, CUSTOMER_NAME STRING, CITY STRING, CUSTOMER_TYPE STRING
);
