USE DATABASE SUPPLYSHIELD;

CREATE OR REPLACE VIEW CURATED.V_STOCKOUT_RISK AS
WITH inv AS (
 SELECT i.PLANT_ID,i.MEDICINE_ID,i.ON_HAND,m.MEDICINE_NAME,m.CRITICALITY,
        m.DAILY_DEMAND,m.UNIT_COST,m.SAFETY_DAYS,
        ROUND(i.ON_HAND / NULLIF(m.DAILY_DEMAND,0),1) AS DAYS_COVER
 FROM RAW.INVENTORY i JOIN RAW.MEDICINES m USING(MEDICINE_ID)
),
ship AS (
 SELECT PLANT_ID,MEDICINE_ID,
        SUM(IFF(STATUS IN ('IN_TRANSIT','ON_TIME'),QTY,0)) AS INCOMING_QTY,
        MAX(IFF(STATUS='DELAYED',DATEDIFF(day,PROMISED_DATE,EXPECTED_DATE),0)) AS MAX_DELAY_DAYS
 FROM RAW.SHIPMENTS GROUP BY 1,2
)
SELECT i.*,COALESCE(s.INCOMING_QTY,0) AS INCOMING_QTY,
       COALESCE(s.MAX_DELAY_DAYS,0) AS MAX_DELAY_DAYS,
       ROUND((i.ON_HAND + COALESCE(s.INCOMING_QTY,0))/NULLIF(i.DAILY_DEMAND,0),1) AS PROJECTED_DAYS_COVER,
       CASE WHEN i.DAYS_COVER < i.SAFETY_DAYS
                  OR (i.ON_HAND + COALESCE(s.INCOMING_QTY,0))/NULLIF(i.DAILY_DEMAND,0) < i.SAFETY_DAYS
            THEN 'HIGH'
            WHEN i.DAYS_COVER < i.SAFETY_DAYS + 5 THEN 'MEDIUM'
            ELSE 'LOW' END AS RISK_LEVEL
FROM inv i LEFT JOIN ship s USING(PLANT_ID,MEDICINE_ID);

CREATE OR REPLACE VIEW CURATED.V_SUPPLY_IMPACT AS
SELECT r.*,o.ORDER_ID,o.CUSTOMER_ID,c.CUSTOMER_NAME,o.QTY AS ORDER_QTY,
       o.REQUIRED_DATE,o.PRIORITY
FROM CURATED.V_STOCKOUT_RISK r
JOIN RAW.ORDERS o ON r.PLANT_ID=o.PLANT_ID AND r.MEDICINE_ID=o.MEDICINE_ID
JOIN RAW.CUSTOMERS c USING(CUSTOMER_ID);

CREATE OR REPLACE VIEW SEMANTIC.V_SUPPLYGRAPH AS
SELECT PLANT_ID AS PLANT,MEDICINE_ID AS PART,MEDICINE_NAME AS MEDICINE,
       CRITICALITY,DAYS_COVER,PROJECTED_DAYS_COVER,RISK_LEVEL,
       INCOMING_QTY,MAX_DELAY_DAYS,DAILY_DEMAND,UNIT_COST,SAFETY_DAYS
FROM CURATED.V_STOCKOUT_RISK;
