USE DATABASE SUPPLYSHIELD;

CREATE OR REPLACE VIEW CURATED.V_RISK_EVIDENCE AS
SELECT r.PLANT_ID,r.MEDICINE_ID,r.MEDICINE_NAME,r.CRITICALITY,
       r.DAYS_COVER,r.PROJECTED_DAYS_COVER,r.RISK_LEVEL,
       r.INCOMING_QTY,r.MAX_DELAY_DAYS,
       s.SUPPLIER_ID,s.SUPPLIER_NAME,s.RELIABILITY_SCORE,
       sh.SHIPMENT_ID,sh.PROMISED_DATE,sh.EXPECTED_DATE,sh.STATUS
FROM CURATED.V_STOCKOUT_RISK r
LEFT JOIN RAW.SHIPMENTS sh
  ON r.PLANT_ID=sh.PLANT_ID AND r.MEDICINE_ID=sh.MEDICINE_ID
LEFT JOIN RAW.SUPPLIERS s
  ON sh.SUPPLIER_ID=s.SUPPLIER_ID;

CREATE OR REPLACE VIEW CURATED.V_INTERVENTION_OPTIONS AS
WITH risk AS (
 SELECT * FROM CURATED.V_STOCKOUT_RISK WHERE RISK_LEVEL IN ('HIGH','MEDIUM')
),
transfer AS (
 SELECT r.PLANT_ID AS TARGET_PLANT,r.MEDICINE_ID,
        p.PLANT_ID AS SOURCE_PLANT,p.ON_HAND AS SOURCE_ON_HAND,
        r.DAILY_DEMAND,r.SAFETY_DAYS,
        GREATEST(0,CEIL(r.DAILY_DEMAND*r.SAFETY_DAYS-r.ON_HAND)) AS REQUIRED_QTY,
        0.12 AS COST_PER_UNIT
 FROM risk r
 JOIN RAW.INVENTORY p ON p.MEDICINE_ID=r.MEDICINE_ID AND p.PLANT_ID<>r.PLANT_ID
 WHERE p.ON_HAND>0
)
SELECT TARGET_PLANT,MEDICINE_ID,SOURCE_PLANT,REQUIRED_QTY,
       ROUND(REQUIRED_QTY*COST_PER_UNIT,2) AS ESTIMATED_TRANSFER_COST
FROM transfer;

CREATE OR REPLACE VIEW SEMANTIC.V_SUPPLYGRAPH AS
SELECT e.PLANT_ID AS PLANT,
       e.MEDICINE_ID AS PART,
       e.MEDICINE_NAME AS MEDICINE,
       e.SUPPLIER_ID AS SUPPLIER,
       e.SUPPLIER_NAME,
       e.CRITICALITY,
       e.DAYS_COVER,
       e.PROJECTED_DAYS_COVER,
       e.RISK_LEVEL,
       e.MAX_DELAY_DAYS,
       e.SHIPMENT_ID,
       e.STATUS AS SHIPMENT_STATUS
FROM CURATED.V_RISK_EVIDENCE e;
